# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        /:title/

# Setup
title:            Maps and Spatial Analysis
tagline:          "My work in GIS and other stuff"
description:      "A blog where a data science student keeps track of what he learns. Geographic Information Systems (GIS), Data Analysis, and more."
url:              https://wilsoncwc.github.io
baseurl:          /
paginate:         3
rss:              atom.xml
logo:             "/public/apple-touch-icon-144x144.png"
lang:             en_SG
webmaster_verifications:
  google: T595DPsAvOjTkNROolIaY6Zb1pe_0nAUpoFkaEUKLkI
repo:           https://github.com/wilsoncwc/wilsoncwc.github.io
excerpt_separator: "<!--excerpt-->"

# Social links
author:
  name:           Wilson Chua
  twitter:        wilsoncwc
  github:         wilsoncwc
  email:          "&#119;&#105;&#108;&#115;&#111;&#110;&#099;&#119;&#099;&#064;&#103;&#109;&#097;&#105;&#108;&#046;&#099;&#111;&#109;"

social:
  name:           Wilson Chua
  links:
    - https://twitter.com/wilsoncwc
    - https://github.com/wilsoncwc

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
