# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            "Maps and Spatial Analysis"
tagline:          "My work in GIS and other stuff"
description:      "A place where I keep track of what I learn. Mostly about GIS, but with other stuff occasionally thrown in."
url:              "https://wilsoncwc.github.io"
baseurl:          "/"

author:
  name:           'Wilson Chua'
  url:            https://twitter.com/wilsoncwc

paginate:         3

# Custom vars
version:
twitter_username:     wilsoncwc
github_username:      wilsoncwc
facebook_username:    wilson7447

github:
  repo:           https://github.com/wilsoncwc/wilsoncwc.github.io
