# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        /:title/

# Setup
title:            Maps and Spatial Analysis
tagline:          "My work in GIS and other stuff"
description:      "A place where I keep track of what I learn."
url:              https://wilsoncwc.github.io
baseurl:          https://wilsoncwc.github.io/
excerpt_separator: "<!--excerpt-->"
paginate:         3
rss:              atom.xml

author:
  name:           Wilson Chua
  twitter:        wilsoncwc
  github:         wilsoncwc
  email:          wilsoncwc@gmail.com

plugins:
  - jekyll-paginate
  - jekyll-sitemap

# Custom vars
version:

github:
  repo:           https://github.com/wilsoncwc/wilsoncwc.github.io
